application: loggergae
version: v1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: .*
  script: api.app

libraries:
- name: webapp2
  version: "2.5.1"
